// [Ace] Incomplete.
class BrassCatcher : HDPickup
{
	override void Tick()
	{
		if (CheckProximity("HDSpent7mm", 128, 1, CPXF_SETTRACER) && tracer)
		{
			let item = HDUPK(tracer);
			item.picktarget = self;
			item.a_hdupkgive();
		}

		Super.Tick();
	}

	Default
	{
		Inventory.PickupSound "misc/w_pkup";
		Inventory.PickupMessage "Brass catcher";
		Inventory.MaxAmount 1;
		HDPickup.MaxUnitAmount 1;
		HDPickup.Bulk 20;
	}

	States
	{
		Spawn:
			BRSC A -1;
			Stop;
	}
}